### ISSUE TITLE
Missing kuttypy firmware for arduino to use with this KuttyPy-GUI

### ISSUE THREAD

**Issue by indraneelpatil** [csparkresearch/KuttyPy-GUI#10]
Hey! Thanks for this great work and making this work available to everyone. From what I have understood after preliminary glances at this work, for the KuttyPy-GUI to work with an arduino, we need to upload the kuttypy firmware to the arduino right? 

If the answer to this question is yes then would you be able to guide me to the path of this firmware for arduino in the repository?

Thanking you in advance.

**Comment by csparkresearch** [comment]
https://github.com/csparkresearch/KuttyPy-GUI/tree/master/docs/firmware
Firmware is in the repository itself. compile/upload instructions are on that page's README.
Upload must be done with an ISP such as USBASP since the bootloader itself is being rewritten..
After that, launch the relevant GUI :
`python3 KuttyPyUno.py `
